# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DockerImageName: 'go-bookstore'
  DockerImageRepo: 'golang-340003/$(DockerImageName)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: "Docker Login"
      inputs:
        containerRegistry: 'gcr-tutorial'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: 'gcr-tutorial'
        repository: '$(DockerImageRepo)'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        addPipelineData: false
        addBaseImageData: false

